name: Deploy to Ubuntu Server
  uses: appleboy/ssh-action@v0.1.5
  with:
    host: ${{ secrets.SERVER_HOST }}
    username: ${{ secrets.SERVER_USER }}
    password: ${{ secrets.SERVER_PASSWORD }}
    port: ${{ secrets.SERVER_PORT }}
    script: |
      mkdir -p ${{ secrets.DEPLOY_PATH }}
      rm -rf ${{ secrets.DEPLOY_PATH }}/build
      scp -r ./build/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}
      cd ${{ secrets.DEPLOY_PATH }}
      pm2 delete react-app || true
      pm2 start npm --name "react-app" -- start
      pm2 save
    debug: true # Enable debugging
